---
title: "Mecha_Car_Challenge"
output: html_document
---

# Mecha Car Challenge
## Deliverable 1

```{r}
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
suppressMessages(library(tidyverse))
```


```{r}
# Read in csv file
MechaCar <- read.csv('./Resources/MechaCar_mpg.csv') 
head(MechaCar)
```

```{r}
#generate multiple linear regression model
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=MechaCar) 
```


```{r}
# generate summary statistics
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=MechaCar))
```
### P-Values below p=.05 threshold for Intercept, Vehicle Length, and Ground Clearance.

### R-Squared Value: 0.7149


## Deliverable 2
```{r}
# read in csv data file
Suspension <- read.csv('./Resources/Suspension_Coil.csv') 
head(Suspension)
```
```{r}
# create summary statistics table
total_summary <- Suspension %>% summarize(meanPSI = mean(Suspension$PSI),
                                          medianPSI = median(Suspension$PSI),
                                          variancePSI = var(Suspension$PSI),
                                          SD_PSI = sd(Suspension$PSI))
```

```{r}
# create summary statiscics by manufacturing lot
lot_summary <- Suspension %>% group_by(Manufacturing_Lot) %>% summarize(mean_lot = mean(PSI),
                                          median_lot = median(PSI),
                                          variance_lot = var(PSI),
                                          SD_lot = sd(PSI), .groups="keep")

```


## Deliverable 3
```{r}
# perform a t-test to determine if the PSI across all manufacturing lots is statistically different from the pop mean
t.test(Suspension$PSI, mu=1500)
```

```{r}
# Perform a t-test to determine if lot #1 is statistically different from the pop mean.
t.test(subset(Suspension, Manufacturing_Lot=="Lot1")$PSI, mu=1500)
```

```{r}
# Perform a t-test to determine if lot #2 is statistically different from the pop mean.
t.test(subset(Suspension, Manufacturing_Lot=="Lot2")$PSI, mu=1500)
```

```{r}
# Perform a t-test to determine if lot #3 is statistically different from the pop mean.
t.test(subset(Suspension, Manufacturing_Lot=="Lot3")$PSI, mu=1500)
```

